# Generated by Django 6.0.5 on 2026-06-02 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=150, unique=True)),
                ('device_name', models.CharField(max_length=255)),
                ('auth_id', models.CharField(max_length=150)),
                ('auth_password_hash', models.CharField(blank=True, max_length=255)),
                ('input_type', models.CharField(choices=[('json', 'json'), ('csv', 'csv')], default='json', max_length=10)),
                ('csv_header_mode', models.CharField(blank=True, choices=[('header_exists', 'header_exists'), ('no_header', 'no_header')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('system_admin', 'system_admin'), ('company_admin', 'company_admin'), ('site_admin', 'site_admin'), ('general_user', 'general_user')], max_length=30)),
                ('login_id', models.CharField(max_length=150, unique=True)),
                ('user_name', models.CharField(max_length=255)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.platformuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='platformuser',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.site'),
        ),
        migrations.CreateModel(
            name='LatestValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=150)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('display_value', models.CharField(blank=True, max_length=255)),
                ('device_timestamp', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('threshold_status', models.CharField(default='normal', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_values', to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_interval_seconds', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='unknown', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='communication_status', to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.site'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.platformuser')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(max_length=150)),
                ('threshold_name', models.CharField(max_length=255)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('lower_limit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('notify_emails', models.TextField()),
                ('suppress_minutes', models.PositiveIntegerField(default=60)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('current_status', models.CharField(default='normal', max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='core.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThresholdEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=150)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('threshold_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
                ('threshold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.threshold')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('column_name', models.CharField(max_length=150)),
                ('display_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('number', 'number'), ('string', 'string'), ('boolean', 'boolean')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.device')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('device', 'column_name'), name='unique_column_name_per_device')],
            },
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('company', 'site_name'), name='unique_site_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='latestvalue',
            constraint=models.UniqueConstraint(fields=('device', 'column_name'), name='unique_latest_value_per_column'),
        ),
    ]
