# Generated by Django 6.0.5 on 2026-06-02 04:02

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_poc_admin(apps, schema_editor):
    PlatformUser = apps.get_model('core', 'PlatformUser')
    PlatformUser.objects.get_or_create(
        login_id='admin',
        defaults={
            'role': 'system_admin',
            'user_name': 'PoC Admin',
            'password_hash': make_password('admin123'),
            'status': 'active',
        },
    )


def delete_poc_admin(apps, schema_editor):
    PlatformUser = apps.get_model('core', 'PlatformUser')
    PlatformUser.objects.filter(login_id='admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_poc_admin, delete_poc_admin),
    ]
