# Generated by Django 6.0.5 on 2026-06-12 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_poc_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('is_error', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
            ],
        ),
        migrations.CreateModel(
            name='ParsedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_timestamp', models.DateTimeField()),
                ('server_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('column_name', models.CharField(max_length=150)),
                ('raw_value', models.JSONField()),
                ('display_value', models.JSONField()),
                ('is_valid', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_data', to='core.device')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.site')),
                ('raw_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parsed_values', to='core.rawdata')),
            ],
            options={
                'indexes': [models.Index(fields=['device', 'device_timestamp'], name='core_parsed_device__e77c36_idx'), models.Index(fields=['device', 'column_name', 'device_timestamp'], name='core_parsed_device__bfede4_idx')],
            },
        ),
    ]
